name: lint

on:
  pull_request:
  schedule:
    - cron: 0 20 * * 0
  workflow_dispatch:

jobs:
  PSScriptAnalyzer:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force
        shell: pwsh

      - name: Check syntax of PowerShell script
        run: Invoke-ScriptAnalyzer -Path .\ -Recurse -EnableExit
        shell: pwsh

  markdown-lint:
    name: Lint markdown files.

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Check syntax of markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
